#!/bin/env bash
curl https://artvee.com/c/japanese-art/?per_page=70 -s | \
grep product-image-link  | cut -d " " -f 2 | \
sed -e "s/href=//g" -e "s/\"//g" > links.txt

for i in `cat links.txt`;
do
    echo $i
    title=$(curl -s $i | grep  data-title | \
        sed -e "s/data-title=//g" -e "s/\"//g" -e "s/\t//g")
     echo $title
     link=$(curl -s $i | grep Download | cut -d " " -f 3 | \
         awk '{print $1;}' | \
         sed -e "s/href=//g" -e "s/\"/*//g" -e "s/>Download<\/a>*//g" )
     echo $link
#     curl  $link > $title.jpg
#     feh --bg-center --bg-fill ~/.dotfiles/scripts/$title
#     sleep 10m
done
# #feh --no-fehbg --bg-scale '/home/sant/Pictures/Fondos/pixelmoon.png'
