#!/bin/env bash
# Manda una notificación mediante herb si la bateria es baja
# Recuerda exportar tu DISPLAY porque sino no puede abrir la interfaz gráfica
export DISPLAY=":0.0"
battery=$(acpi | awk '{print $4}' | sed 's/%,//g')
status=$(acpi | awk '{print $3}' | sed 's/,//g')

if [ $battery -lt 10 ] && [ $status != 'Charging' ]
then
    herbe "Conecta tu laptop."

fi


if [ $status = 'Full' ]
then
    herbe "Desconectar la laptop"

fi
